[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  # Set NODE_VERSION if you need a specific Node.js version on Netlify (optional)
  # NODE_VERSION = "18"

[dev]
  port = 5173
  command = "npm run dev"
